---
services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    restart: unless-stopped
    networks:
      - caddy
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - ${SABNZBD_PORT}:8080
    volumes:
      - ./data/sabnzbd/config:/config
      - /mnt/jellyfin/Downloads:/downloads

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    networks:
      - caddy
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - ${SONARR_PORT}:8989
    volumes:
      - ./data/sonarr/config:/config
      - /mnt/jellyfin:/data
      - /mnt/jellyfin/Downloads:/downloads

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    networks:
      - caddy
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - ${RADARR_PORT}:7878
    volumes:
      - ./data/radarr/config:/config
      - /mnt/jellyfin:/data
      - /mnt/jellyfin/Downloads:/downloads

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    networks:
      - caddy
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - ${PROWLARR_PORT}:9696
    volumes:
      - ./data/prowlarr/config:/config

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    restart: unless-stopped
    networks:
      - caddy
    environment:
      - LOG_LEVEL=debug
      - TZ=${TZ}
    ports:
      - ${JELLYSEERR_PORT}:5055
    volumes:
      - ./data/jellyseerr/app/config:/app/config
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3

networks:
  caddy:
    external: true
